name: Ejecutar pruebas

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Descargar el repo
      - name: Descargar repo
        uses: actions/checkout@v4

      # Instalar Python
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Instalar dependencias si existen
      - name: Instalar dependencias
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No dependencies"; fi

      # Instalar pytest por si no está en requirements.txt
      - name: Instalar pytest
        run: pip install pytest

      # Ejecutar pruebas
      - name: Ejecutar pruebas
        run: pytest -v